name: tests
on: [push]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  run-tests-edge:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4.5.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run Edge Robot Tests
      uses: nick-fields/retry@v2.8.3
      with:
        timeout_seconds: 15
        command: robot tests

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: reportsEdge
        path: reports


  generate_report:
    if: always()
    needs: [run-tests-edge]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download reportsChrome
      uses: actions/download-artifact@v3
      with:
        name: reportsEdge
        path: reports
    - name: combine reports
      run: rebot -o reports/output.xml reports/*.xml
    - name: Send report to commit
      uses: joonvena/robotframework-reporter-action@v2.1
      with:
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}
        show_passed_tests: false
