name: Robot Framework Practices
on: [push]
jobs:
  robot_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Execute tests
      uses: joonvena/robotframework-docker-action@v0.1
      env:
        BROWSER: chrome
        ROBOT_TESTS_DIR: ./Google_Search/Tests
        ROBOT_REPORTS_DIR: ./reports
