name: End-to-end tests 🧪
on: [push]
jobs:
  robot_test:
    runs-on: ubuntu-latest
    name: Run Robot Framework Tests
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      run: [python -m pip install --upgrade pip; pip install -r requirements.txt]
    - name: Robot Framework
      uses: joonvena/robotframework-docker-action@v1.0
      with:
        robot_tests_dir: Google_Search/Tests/
